# Generated by Django 5.0.6 on 2024-06-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='course',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='meeting_time',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='room',
        ),
    ]
