# Generated by Django 5.0.6 on 2024-06-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0002_alter_lesson_instructor_alter_stream_instructor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='is_institution_set',
            new_name='is_application_accepted',
        ),
    ]
