# Generated by Django 5.0.6 on 2024-06-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0003_rename_is_institution_set_userdata_is_application_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='is_institution_approved',
            field=models.BooleanField(default=False),
        ),
    ]
