# Generated by Django 5.0.6 on 2024-06-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0004_institution_is_institution_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingtime',
            name='pid',
        ),
        migrations.AddField(
            model_name='meetingtime',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
