# Generated by Django 5.0.6 on 2024-06-23 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0005_remove_meetingtime_pid_meetingtime_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='meeting_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeapp.meetingtime'),
        ),
    ]
