# Generated by Django 5.0.6 on 2024-06-23 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0006_alter_stream_meeting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='meeting_time',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='meeting_time',
        ),
    ]
