# Generated by Django 5.0.6 on 2024-07-15 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0006_timeset_meetingtime_timeset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='timeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeapp.timeset'),
        ),
    ]
