# Generated by Django 5.0.6 on 2024-06-23 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0007_remove_lesson_meeting_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='meeting_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeapp.meetingtime'),
        ),
        migrations.AddField(
            model_name='stream',
            name='meeting_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeapp.meetingtime'),
        ),
    ]
