# Generated by Django 5.0.6 on 2024-06-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0008_lesson_meeting_time_stream_meeting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='stream_id',
        ),
        migrations.AddField(
            model_name='stream',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
