# Generated by Django 5.0.6 on 2024-07-17 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0009_stream_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='timeapp.role'),
        ),
    ]
